[[key]]
name = "Esc"
x = 25.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F1"
x = 100.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F2"
x = 155.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F3"
x = 210.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F4"
x = 265.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F5"
x = 345.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F6"
x = 400.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F7"
x = 455.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F8"
x = 510.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F9"
x = 590.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F10"
x = 645.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F11"
x = 700.0
y = 25.0
width = 50
height = 50

[[key]]
name = "F12"
x = 755.0
y = 25.0
width = 50
height = 50

[[key]]
name = "`"
x = 25.0
y = 80.0
width = 50
height = 50
keycode = "grave"

[[key]]
name = "1"
x = 80.0
y = 80.0
width = 50
height = 50

[[key]]
name = "2"
x = 135.0
y = 80.0
width = 50
height = 50

[[key]]
name = "3"
x = 190.0
y = 80.0
width = 50
height = 50

[[key]]
name = "4"
x = 245.0
y = 80.0
width = 50
height = 50

[[key]]
name = "5"
x = 300.0
y = 80.0
width = 50
height = 50

[[key]]
name = "6"
x = 355.0
y = 80.0
width = 50
height = 50

[[key]]
name = "7"
x = 410.0
y = 80.0
width = 50
height = 50

[[key]]
name = "8"
x = 465.0
y = 80.0
width = 50
height = 50

[[key]]
name = "9"
x = 520.0
y = 80.0
width = 50
height = 50

[[key]]
name = "0"
x = 575.0
y = 80.0
width = 50
height = 50

[[key]]
name = "-"
x = 630.0
y = 80.0
width = 50
height = 50
keycode = "minus"

[[key]]
name = "="
x = 685.0
y = 80.0
width = 50
height = 50
keycode = "equal"

[[key]]
name = "Backspace"
x = 767.5
y = 80.0
width = 105
height = 50

[[key]]
name = "Tab"
x = 40.0
y = 135.0
width = 80
height = 50

[[key]]
name = "Q"
x = 110.0
y = 135.0
width = 50
height = 50

[[key]]
name = "W"
x = 165.0
y = 135.0
width = 50
height = 50

[[key]]
name = "E"
x = 220.0
y = 135.0
width = 50
height = 50

[[key]]
name = "R"
x = 275.0
y = 135.0
width = 50
height = 50

[[key]]
name = "T"
x = 330.0
y = 135.0
width = 50
height = 50

[[key]]
name = "Y"
x = 385.0
y = 135.0
width = 50
height = 50

[[key]]
name = "U"
x = 440.0
y = 135.0
width = 50
height = 50

[[key]]
name = "I"
x = 495.0
y = 135.0
width = 50
height = 50

[[key]]
name = "O"
x = 550.0
y = 135.0
width = 50
height = 50

[[key]]
name = "P"
x = 605.0
y = 135.0
width = 50
height = 50

[[key]]
name = "["
x = 660.0
y = 135.0
width = 50
height = 50
keycode = "leftbrace"

[[key]]
name = "]"
x = 715.0
y = 135.0
width = 50
height = 50
keycode = "rightbrace"

[[key]]
name = "\\"
x = 780.0
y = 135.0
width = 70
height = 50
keycode = "backslash"

[[key]]
name = "Caps Lock"
x = 47.5
y = 190.0
width = 95
height = 50
keycode = "capslock"

[[key]]
name = "A"
x = 125.0
y = 190.0
width = 50
height = 50

[[key]]
name = "S"
x = 180.0
y = 190.0
width = 50
height = 50

[[key]]
name = "D"
x = 235.0
y = 190.0
width = 50
height = 50

[[key]]
name = "F"
x = 290.0
y = 190.0
width = 50
height = 50

[[key]]
name = "G"
x = 345.0
y = 190.0
width = 50
height = 50

[[key]]
name = "H"
x = 400.0
y = 190.0
width = 50
height = 50

[[key]]
name = "J"
x = 455.0
y = 190.0
width = 50
height = 50

[[key]]
name = "K"
x = 510.0
y = 190.0
width = 50
height = 50

[[key]]
name = "L"
x = 565.0
y = 190.0
width = 50
height = 50

[[key]]
name = ";"
x = 620.0
y = 190.0
width = 50
height = 50
keycode = "semicolon"

[[key]]
name = "'"
x = 675.0
y = 190.0
width = 50
height = 50
keycode = "apostrophe"

[[key]]
name = "Enter"
x = 760.0
y = 190.0
width = 110
height = 50

[[key]]
name = "L. Shift"
x = 60.0
y = 245.0
width = 120
height = 50
keycode = "leftshift"

[[key]]
name = "Z"
x = 150.0
y = 245.0
width = 50
height = 50

[[key]]
name = "X"
x = 205.0
y = 245.0
width = 50
height = 50

[[key]]
name = "C"
x = 260.0
y = 245.0
width = 50
height = 50

[[key]]
name = "V"
x = 315.0
y = 245.0
width = 50
height = 50

[[key]]
name = "B"
x = 370.0
y = 245.0
width = 50
height = 50

[[key]]
name = "N"
x = 425.0
y = 245.0
width = 50
height = 50

[[key]]
name = "M"
x = 480.0
y = 245.0
width = 50
height = 50

[[key]]
name = ","
x = 535.0
y = 245.0
width = 50
height = 50
keycode = "comma"

[[key]]
name = "."
x = 590.0
y = 245.0
width = 50
height = 50
keycode = "dot"

[[key]]
name = "/"
x = 645.0
y = 245.0
width = 50
height = 50
keycode = "slash"

[[key]]
name = "R. Shift"
x = 745.0
y = 245.0
width = 140
height = 50
keycode = "rightshift"

[[key]]
name = "L. Ctrl"
x = 35.0
y = 300.0
width = 70
height = 50
keycode = "leftctrl"

[[key]]
name = "L. Super"
x = 105.0
y = 300.0
width = 60
height = 50
keycode = "leftmeta"

[[key]]
name = "L. Alt"
x = 175.0
y = 300.0
width = 70
height = 50
keycode = "leftalt"

[[key]]
name = "Space"
x = 365.0
y = 300.0
width = 300
height = 50

[[key]]
name = "R. Alt"
x = 555.0
y = 300.0
width = 70
height = 50
keycode = "rightalt"

[[key]]
name = "R. Super"
x = 625.0
y = 300.0
width = 60
height = 50
keycode = "rightmeta"

[[key]]
name = "Menu"
x = 690.0
y = 300.0
width = 60
height = 50

[[key]]
name = "R. Ctrl"
x = 770.0
y = 300.0
width = 90
height = 50
keycode = "rightctrl"

[[key]]
name = "PrtSc"
x = 865.0
y = 25.0
width = 50
height = 50
keycode = "sysrq"

[[key]]
name = "ScrollLk"
x = 920.0
y = 25.0
width = 50
height = 50
keycode = "scrolllock"

[[key]]
name = "Pause"
x = 975.0
y = 25.0
width = 50
height = 50

[[key]]
name = "Ins"
x = 865.0
y = 80.0
width = 50
height = 50
keycode = "insert"

[[key]]
name = "Home"
x = 920.0
y = 80.0
width = 50
height = 50

[[key]]
name = "PgUp"
x = 975.0
y = 80.0
width = 50
height = 50
keycode = "pageup"

[[key]]
name = "Del"
x = 865.0
y = 135.0
width = 50
height = 50
keycode = "delete"

[[key]]
name = "End"
x = 920.0
y = 135.0
width = 50
height = 50

[[key]]
name = "PgDn"
x = 975.0
y = 135.0
width = 50
height = 50
keycode = "pagedown"

[[key]]
name = "Up"
x = 920.0
y = 245.0
width = 50
height = 50
keycode = "up"

[[key]]
name = "Left"
x = 865.0
y = 300.0
width = 50
height = 50
keycode = "left"

[[key]]
name = "Down"
x = 920.0
y = 300.0
width = 50
height = 50
keycode = "down"

[[key]]
name = "Right"
x = 975.0
y = 300.0
width = 50
height = 50
keycode = "right"
