# Default 85% (Tenkeyless) Keyboard Layout
# Coordinates are top-left and will be scaled by the application.
# Standard key unit size is 50x50, with spacing of 5 units.
# `left` coordinates increase to the right, `top` coordinates increase downwards.

# Unit dimensions (for easier calculation)
# u = key unit size (e.g., 50 for a 1U key width/height)
# s = spacing (e.g., 5)

# Function Row (top = -25)
[[key]]
name = "Esc"
left = -25 # 0 - 50/2
top = -25  # 0 - 50/2
width = 50
height = 50
# keycode = "esc"

[[key]] # Gap of 25 (75 - (0+50)) -> new gap of 25. (0-25+50)+25 = 50. New left = 50
name = "F1"
left = 50  # 75 - 50/2
top = -25 # 0 - 50/2
width = 50
height = 50
# keycode = "f1"

[[key]] # 130 - (75+50) = 5. (50+50)+5 = 105
name = "F2"
left = 105 # 130 - 50/2
top = -25
width = 50
height = 50

[[key]] # 185 - (130+50) = 5. (105+50)+5 = 160
name = "F3"
left = 160 # 185 - 50/2
top = -25
width = 50
height = 50

[[key]] # 240 - (185+50) = 5. (160+50)+5 = 215
name = "F4"
left = 215 # 240 - 50/2
top = -25
width = 50
height = 50

# Gap of 25 (320 - (240+50)) = 30. (215+50)+30 = 295
[[key]]
name = "F5"
left = 295 # 320 - 50/2
top = -25
width = 50
height = 50

[[key]] # 375 - (320+50) = 5. (295+50)+5 = 350
name = "F6"
left = 350 # 375 - 50/2
top = -25
width = 50
height = 50

[[key]] # 430 - (375+50) = 5. (350+50)+5 = 405
name = "F7"
left = 405 # 430 - 50/2
top = -25
width = 50
height = 50

[[key]] # 485 - (430+50) = 5. (405+50)+5 = 460
name = "F8"
left = 460 # 485 - 50/2
top = -25
width = 50
height = 50

# Gap of 25 (565 - (485+50)) = 30. (460+50)+30 = 540
[[key]]
name = "F9"
left = 540 # 565 - 50/2
top = -25
width = 50
height = 50

[[key]] # 620 - (565+50) = 5. (540+50)+5 = 595
name = "F10"
left = 595 # 620 - 50/2
top = -25
width = 50
height = 50

[[key]] # 675 - (620+50) = 5. (595+50)+5 = 650
name = "F11"
left = 650 # 675 - 50/2
top = -25
width = 50
height = 50

[[key]] # 730 - (675+50) = 5. (650+50)+5 = 705
name = "F12"
left = 705 # 730 - 50/2
top = -25
width = 50
height = 50
# keycode = "f12"

# Number Row (y = 55 -> top = 55 - 25 = 30)
[[key]]
name = "`"
left = -25 # 0 - 50/2
top = 30   # 55 - 50/2
width = 50
height = 50
keycode = "grave"

[[key]] # 55 - (0+50) = 5. (-25+50)+5 = 30
name = "1"
left = 30  # 55 - 50/2
top = 30
width = 50
height = 50
# keycode = "1"

[[key]] # 110 - (55+50) = 5. (30+50)+5 = 85
name = "2"
left = 85 # 110 - 50/2
top = 30
width = 50
height = 50

[[key]] # 165 - (110+50) = 5. (85+50)+5 = 140
name = "3"
left = 140 # 165 - 50/2
top = 30
width = 50
height = 50

[[key]] # 220 - (165+50) = 5. (140+50)+5 = 195
name = "4"
left = 195 # 220 - 50/2
top = 30
width = 50
height = 50

[[key]] # 275 - (220+50) = 5. (195+50)+5 = 250
name = "5"
left = 250 # 275 - 50/2
top = 30
width = 50
height = 50

[[key]] # 330 - (275+50) = 5. (250+50)+5 = 305
name = "6"
left = 305 # 330 - 50/2
top = 30
width = 50
height = 50

[[key]] # 385 - (330+50) = 5. (305+50)+5 = 360
name = "7"
left = 360 # 385 - 50/2
top = 30
width = 50
height = 50

[[key]] # 440 - (385+50) = 5. (360+50)+5 = 415
name = "8"
left = 415 # 440 - 50/2
top = 30
width = 50
height = 50

[[key]] # 495 - (440+50) = 5. (415+50)+5 = 470
name = "9"
left = 470 # 495 - 50/2
top = 30
width = 50
height = 50

[[key]] # 550 - (495+50) = 5. (470+50)+5 = 525
name = "0"
left = 525 # 550 - 50/2
top = 30
width = 50
height = 50

[[key]] # 605 - (550+50) = 5. (525+50)+5 = 580
name = "-"
left = 580 # 605 - 50/2
top = 30
width = 50
height = 50
keycode = "minus"

[[key]] # 660 - (605+50) = 5. (580+50)+5 = 635
name = "="
left = 635 # 660 - 50/2
top = 30
width = 50
height = 50
keycode = "equal"

[[key]] # 715 - (660+50) = 5. (635+50)+5 = 690. Old x was center. 715 - 105/2 = 662.5
name = "Backspace"
left = 690 # 715 - 105/2 = 662.5. Let's use 690.
top = 30   # 55 - 50/2
width = 105 # Wider
height = 50
# keycode = "backspace"

# Top Alpha Row (QWERTY) (y = 110 -> top = 110 - 25 = 85)
[[key]]
name = "Tab"
left = 0    # 40 - 80/2. Let's align to edge: -25.
top = 85    # 110 - 50/2
width = 75  # Standard 1.5U. Old width 80.
height = 50
# keycode = "tab"

[[key]] # Old x 85. Tab old x 40, width 80. (40+80/2) = 80. 85-80=5. New Tab: (-25+75)+5 = 55.
name = "Q"
left = 55  # 85 - 50/2
top = 85
width = 50
height = 50

[[key]] # 140-(85+50)=5. (55+50)+5 = 110
name = "W"
left = 110 # 140 - 50/2
top = 85
width = 50
height = 50

[[key]] # 195-(140+50)=5. (110+50)+5 = 165
name = "E"
left = 165 # 195 - 50/2
top = 85
width = 50
height = 50

[[key]] # 250-(195+50)=5. (165+50)+5 = 220
name = "R"
left = 220 # 250 - 50/2
top = 85
width = 50
height = 50

[[key]] # 305-(250+50)=5. (220+50)+5 = 275
name = "T"
left = 275 # 305 - 50/2
top = 85
width = 50
height = 50

[[key]] # 360-(305+50)=5. (275+50)+5 = 330
name = "Y"
left = 330 # 360 - 50/2
top = 85
width = 50
height = 50

[[key]] # 415-(360+50)=5. (330+50)+5 = 385
name = "U"
left = 385 # 415 - 50/2
top = 85
width = 50
height = 50

[[key]] # 470-(415+50)=5. (385+50)+5 = 440
name = "I"
left = 440 # 470 - 50/2
top = 85
width = 50
height = 50

[[key]] # 525-(470+50)=5. (440+50)+5 = 495
name = "O"
left = 495 # 525 - 50/2
top = 85
width = 50
height = 50

[[key]] # 580-(525+50)=5. (495+50)+5 = 550
name = "P"
left = 550 # 580 - 50/2
top = 85
width = 50
height = 50

[[key]] # 635-(580+50)=5. (550+50)+5 = 605
name = "["
left = 605 # 635 - 50/2
top = 85
width = 50
height = 50
keycode = "leftbrace"

[[key]] # 690-(635+50)=5. (605+50)+5 = 660
name = "]"
left = 660 # 690 - 50/2
top = 85
width = 50
height = 50
keycode = "rightbrace"

[[key]] # 745-(690+50)=5. (660+50)+5 = 715. Old x 745, w 70. 745-70/2 = 710.
name = "\\"
left = 715 # Use 715 to maintain spacing
top = 85
width = 70 # Often wider
height = 50
keycode = "backslash"

# Middle Alpha Row (ASDF) (y = 165 -> top = 165 - 25 = 140)
[[key]] # Old x 47, w 95. 47 - 95/2 = -0.5. Let's use 0 for 1.75U Caps.
name = "Caps Lock"
left = -12.5 # Standard 1.75U key. (0-25) + (50+5) + (50*0.25) = -25+55+12.5 = 42.5. Let's use (-25 + (75-50)/2) = -25 + 12.5 = -12.5
top = 140   # 165 - 50/2
width = 87.5 # 1.75U key. 50 * 1.75 = 87.5
height = 50
keycode = "capslock"

[[key]] # Old x 100. Caps old x 47, w 95. (47+95/2) = 94.5. 100-94.5=5.5. New Caps (-12.5+87.5)+5 = 80.
name = "A"
left = 80  # 100 - 50/2
top = 140
width = 50
height = 50

[[key]] # 155-(100+50)=5. (80+50)+5 = 135
name = "S"
left = 135 # 155 - 50/2
top = 140
width = 50
height = 50

[[key]] # 210-(155+50)=5. (135+50)+5 = 190
name = "D"
left = 190 # 210 - 50/2
top = 140
width = 50
height = 50

[[key]] # 265-(210+50)=5. (190+50)+5 = 245
name = "F"
left = 245 # 265 - 50/2
top = 140
width = 50
height = 50

[[key]] # 320-(265+50)=5. (245+50)+5 = 300
name = "G"
left = 300 # 320 - 50/2
top = 140
width = 50
height = 50

[[key]] # 375-(320+50)=5. (300+50)+5 = 355
name = "H"
left = 355 # 375 - 50/2
top = 140
width = 50
height = 50

[[key]] # 430-(375+50)=5. (355+50)+5 = 410
name = "J"
left = 410 # 430 - 50/2
top = 140
width = 50
height = 50

[[key]] # 485-(430+50)=5. (410+50)+5 = 465
name = "K"
left = 465 # 485 - 50/2
top = 140
width = 50
height = 50

[[key]] # 540-(485+50)=5. (465+50)+5 = 520
name = "L"
left = 520 # 540 - 50/2
top = 140
width = 50
height = 50

[[key]] # 595-(540+50)=5. (520+50)+5 = 575
name = ";"
left = 575 # 595 - 50/2
top = 140
width = 50
height = 50
keycode = "semicolon"

[[key]] # 650-(595+50)=5. (575+50)+5 = 630
name = "'"
left = 630 # 650 - 50/2
top = 140
width = 50
height = 50
keycode = "apostrophe"

[[key]] # Old x 735, w 110. (735 - 110/2) = 680. Old "'" x 650, w 50. (650+50/2)=675. 735-675=60. (630+50)+5 = 685.
name = "Enter"
left = 685 # Use 685. Standard Enter is ~2.25U, this was 110 (2.2U).
top = 140
width = 100 # Standard 2.25U is 112.5. Let's make it fit better. Previous 110. This is 100 now.
height = 50
# keycode = "enter"

# Bottom Alpha Row (ZXCV) (y = 220 -> top = 220 - 25 = 195)
[[key]] # Old x 60, w 120. (60 - 120/2) = 0. Let's use -25 for standard 2.25U LShift.
name = "Shift"
left = -25 # Standard 2.25U LShift
top = 195   # 220 - 50/2
width = 112.5 # 2.25 * 50
height = 50
keycode = "leftshift"

[[key]] # Old x 125. LShift old x 60, w 120. (60+120/2)=120. 125-120=5. New LShift (-25+112.5)+5 = 92.5
name = "Z"
left = 92.5 # 125 - 50/2
top = 195
width = 50
height = 50

[[key]] # 180-(125+50)=5. (92.5+50)+5 = 147.5
name = "X"
left = 147.5 # 180 - 50/2
top = 195
width = 50
height = 50

[[key]] # 235-(180+50)=5. (147.5+50)+5 = 202.5
name = "C"
left = 202.5 # 235 - 50/2
top = 195
width = 50
height = 50

[[key]] # 290-(235+50)=5. (202.5+50)+5 = 257.5
name = "V"
left = 257.5 # 290 - 50/2
top = 195
width = 50
height = 50

[[key]] # 345-(290+50)=5. (257.5+50)+5 = 312.5
name = "B"
left = 312.5 # 345 - 50/2
top = 195
width = 50
height = 50

[[key]] # 400-(345+50)=5. (312.5+50)+5 = 367.5
name = "N"
left = 367.5 # 400 - 50/2
top = 195
width = 50
height = 50

[[key]] # 455-(400+50)=5. (367.5+50)+5 = 422.5
name = "M"
left = 422.5 # 455 - 50/2
top = 195
width = 50
height = 50

[[key]] # 510-(455+50)=5. (422.5+50)+5 = 477.5
name = ","
left = 477.5 # 510 - 50/2
top = 195
width = 50
height = 50
keycode = "comma"

[[key]] # 565-(510+50)=5. (477.5+50)+5 = 532.5
name = "."
left = 532.5 # 565 - 50/2
top = 195
width = 50
height = 50
keycode = "dot"

[[key]] # 620-(565+50)=5. (532.5+50)+5 = 587.5
name = "/"
left = 587.5 # 620 - 50/2
top = 195
width = 50
height = 50
keycode = "slash"

[[key]] # Old x 720, w 140. (720-140/2)=650. Old "/" x 620, w 50. (620+50/2)=645. 720-645=75. (587.5+50)+5 = 642.5.
name = "Shift" # R. Shift
left = 642.5 # This makes it a 2.75U key based on its old width 140. (785-5) - 642.5 = 137.5. (2.75*50 = 137.5)
top = 195
width = 137.5 # Was 140. Standard is 2.75U.
height = 50
keycode = "rightshift"

# Bottom Row (Modifiers & Space) (y = 275 -> top = 275 - 25 = 250)
[[key]] # Old x 35, w 70. (35-70/2)=0. Let's use -25 for 1.25U Ctrl.
name = "Ctrl"
left = -25 # Standard 1.25U
top = 250   # 275 - 50/2
width = 62.5 # 1.25 * 50
height = 50
keycode = "leftctrl"

[[key]] # Old x 105, w 60. LCtrl old x 35, w 70. (35+70/2)=70. 105-70=35. New LCtrl (-25+62.5)+5 = 42.5
name = "Super"
left = 42.5 # Standard 1.25U
top = 250
width = 62.5 # Was 60. Standard 1.25U
height = 50
keycode = "leftmeta"

[[key]] # Old x 175, w 70. Super old x 105, w 60. (105+60/2)=135. 175-135=40. New Super (42.5+62.5)+5 = 110
name = "Alt"
left = 110 # Standard 1.25U
top = 250
width = 62.5 # Was 70. Standard 1.25U
height = 50
keycode = "leftalt"

[[key]] # Old x 365, w 300. Alt old x 175, w 70. (175+70/2)=210. 365-210=155. New Alt (110+62.5)+5 = 177.5.
name = "Space"
left = 177.5 # Space. Standard 6.25U. 6.25*50 = 312.5.
top = 250
width = 312.5 # Was 300. Standard 6.25U.
height = 50
# keycode = "space"

[[key]] # Old x 555, w 70. Space old x 365, w 300. (365+300/2)=515. 555-515=40. New Space (177.5+312.5)+5 = 495
name = "Alt" # R. Alt
left = 495 # Standard 1.25U
top = 250
width = 62.5 # Was 70. Standard 1.25U
height = 50
keycode = "rightalt"

[[key]] # Old x 625, w 60. RAlt old x 555, w 70. (555+70/2)=590. 625-590=35. New RAlt (495+62.5)+5 = 562.5
name = "Super" # R. Super
left = 562.5 # Standard 1.25U
top = 250
width = 62.5 # Was 60. Standard 1.25U
height = 50
keycode = "rightmeta"

[[key]] # Old x 690, w 60. RSuper old x 625, w 60. (625+60/2)=655. 690-655=35. New RSuper (562.5+62.5)+5 = 630
name = "Menu"
left = 630 # Standard 1.25U (or 1U). Let's use 1.25U for consistency here.
top = 250
width = 62.5 # Was 60.
height = 50
# keycode = "menu"

[[key]] # Old x 770, w 90. Menu old x 690, w 60. (690+60/2)=720. 770-720=50. New Menu (630+62.5)+5 = 697.5
name = "Ctrl" # R. Ctrl
left = 697.5 # Standard 1.25U
top = 250
width = 62.5 # Was 90. Standard 1.25U.
height = 50
keycode = "rightctrl"
# End of main block. Rightmost edge is 697.5 + 62.5 = 760. Matches Backspace end 690+105 = 795 (too wide). Matches Enter end 685+100=785. RShift 642.5+137.5 = 780.
# Let's adjust the rightmost keys of the main block to align around 780-785.
# Backspace: left=680, width=105. (ends 785)
# Enter: left=685, width=100. (ends 785)
# RShift: left=642.5, width=137.5 (ends 780)
# RCtrl: left=717.5, width=62.5 (ends 780) (Menu becomes 1U, left=655, width=50, RCtrl left=710, width=70)
# Let's try to keep RCtrl as 1.25U.
# RCtrl: left=717.5, width=62.5 (ends 780)
# Menu: left= (717.5-5-62.5) = 650, width=62.5
# RSuper: left = (650-5-62.5) = 582.5, width=62.5
# RAlt: left = (582.5-5-62.5) = 515, width=62.5
# Space: width = (515-5) - 177.5 = 332.5. Space left = 177.5
# This makes space very large. Let's re-evaluate from standard sizes.
# LCtrl (1.25U) = -25 to 37.5
# LSuper (1.25U) = 42.5 to 105
# LAlt (1.25U) = 110 to 172.5
# Space (6.25U) = 177.5 to 490
# RAlt (1.25U) = 495 to 557.5
# RSuper (1.25U) = 562.5 to 625
# Menu (1U) = 630 to 680
# RCtrl (1.25U) = 685 to 747.5. (This is about 15U wide total: 15*50 - 10*5 = 750-50 = 700. Add 2*25 for edges = 750)
# Total width of bottom row keys: 1.25+1.25+1.25+6.25+1.25+1.25+1+1.25 = 14U.
# 14 * 50 (key) + 7 * 5 (space) = 700 + 35 = 735. (If 8 keys, 7 spaces).
# If edge aligned: -25 to 735-25 = 710.
# Let's re-do bottom row based on this:
# LCtrl: left = -25, width = 62.5
# LSuper: left = -25 + 62.5 + 5 = 42.5, width = 62.5
# LAlt: left = 42.5 + 62.5 + 5 = 110, width = 62.5
# Space: left = 110 + 62.5 + 5 = 177.5, width = 312.5 (6.25U)
# RAlt: left = 177.5 + 312.5 + 5 = 495, width = 62.5
# RSuper: left = 495 + 62.5 + 5 = 562.5, width = 62.5
# Menu: left = 562.5 + 62.5 + 5 = 630, width = 50 (1U)
# RCtrl: left = 630 + 50 + 5 = 685, width = 62.5
# Max right extent: 685 + 62.5 = 747.5.
# Backspace: width 105. Ends at 747.5. left = 747.5 - 105 = 642.5
# Enter: width 100. Ends at 747.5. left = 747.5 - 100 = 647.5
# RShift: width 137.5. Ends at 747.5. left = 747.5 - 137.5 = 610
# This seems more consistent.

# Navigation Cluster (Original x values: PrtSc 840, Ins 840, Del 840)
# (Original y values: PrtSc 0, Ins 55, Del 110)
# Let nav cluster start at left = 780 after a gap from main block (ends ~750)
# Nav cluster base left: 815 (derived from original x=840, width=50)

[[key]]
name = "PrtSc"
left = 815
top = -25           # 0 - 50/2
width = 50
height = 50
keycode = "sysrq"

[[key]]
name = "Scroll Lock"
left = 870
top = -25
width = 50
height = 50
keycode = "scrolllock"

[[key]]
name = "Pause"
left = 925
top = -25
width = 50
height = 50
# keycode = "pause"

# Middle Nav Row (top = 55 - 25 = 30)
[[key]]
name = "Ins" # Insert
left = 815
top = 30             # 55 - 50/2
width = 50
height = 50
keycode = "insert"

[[key]]
name = "Home"
left = 870
top = 30
width = 50
height = 50
# keycode = "home"

[[key]]
name = "PgUp" # Page Up
left = 925
top = 30
width = 50
height = 50
keycode = "pageup"

# Bottom Nav Row (top = 110 - 25 = 85)
[[key]]
name = "Del" # Delete
left = 815
top = 85             # 110 - 50/2
width = 50
height = 50
keycode = "delete"

[[key]]
name = "End"
left = 870
top = 85
width = 50
height = 50
# keycode = "end"

[[key]]
name = "PgDn" # Page Down
left = 925
top = 85
width = 50
height = 50
keycode = "pagedown"

# Arrow Keys (Original y: Up 220, Left/Down/Right 275)
# Align arrows below nav cluster. Nav cluster ends at top = 85+50 = 135. Gap of 55. Arrow top = 190.
# Up Key: y = 220 -> top = 195. Centered with Home/End. left = nav_base_left + 55
# Left/Down/Right: y = 275 -> top = 250.

[[key]]
name = "Up"
left = 870
top = 195                 # y=220 -> top = 195
width = 50
height = 50
keycode = "up"

[[key]]
name = "Left"
left = 815
top = 250            # y=275 -> top = 250
width = 50
height = 50
keycode = "left"

[[key]]
name = "Down"
left = 870
top = 250
width = 50
height = 50
keycode = "down"

[[key]]
name = "Right"
left = 925
top = 250
width = 50
height = 50
keycode = "right"
# Final check of main block right edge alignment.
# Backspace: old x=715, w=105. Target right edge: 747.5. new left = 747.5 - 105 = 642.5. (Original: 715 - 105/2 = 662.5)
# Enter: old x=735, w=110. Target right edge: 747.5. new left = 747.5 - 110 = 637.5. (Original: 735 - 110/2 = 680)
# RShift: old x=720, w=140. Target right edge: 747.5. new left = 747.5 - 140 = 607.5. (Original: 720 - 140/2 = 650)
# Let's use the derived standard layout positions for bottom row and adjust others to match that width.
# Re-adjusting keys based on a 15U wide main block (from -25 to 747.5, total width 772.5)
# Max right extent of number row / QWERTY row / ASDF row should be 747.5
# Number Row: Backspace (currently width 105). Ends at 747.5. left = 747.5 - 105 = 642.5
# Previous key "=" ends at 635+50=685. Gap of 642.5 - 685 = -42.5 (overlap). This is not good.
# Let 1U = 50, space = 5.
# Esc (1U): -25 to 25
# (gap 25)
# F1-F4 (4*50 + 3*5 = 215): 50 to 265
# (gap 30)
# F5-F8 (4*50 + 3*5 = 215): 295 to 510
# (gap 30)
# F9-F12 (4*50 + 3*5 = 215): 540 to 755. Max extent 755.

# Number Row (14 keys, 1U each typically, except Backspace)
# ` to = : 13 keys * 50 + 12 * 5 = 650 + 60 = 710. Starts at -25. Ends at -25+710 = 685.
# Backspace (2U = 100): left = 685 + 5 = 690. Ends at 690+100 = 790. This is wider than F-row.
# Let's make Backspace 1.5U = 75. left = 685+5 = 690. Ends 690+75 = 765. Closer.
# Original Backspace width was 105. Let's keep it. left = 685+5 = 690. Ends 690+105 = 795.

# QWERTY row
# Tab (1.5U=75): left = -25. Ends 50.
# Q to P (10*50 + 9*5 = 545): left = 50+5 = 55. Ends 55+545 = 600.
# [ (1U): left = 600+5 = 605. Ends 655.
# ] (1U): left = 655+5 = 660. Ends 710.
# \ (1.5U=75, was 70): left = 710+5 = 715. Ends 715+75 = 790.

# ASDF row
# CapsLock (1.75U=87.5): left = -25. Ends 62.5. (original -12.5, w 87.5)
# A to L (9*50 + 8*5 = 490): left = 62.5+5 = 67.5. Ends 67.5+490 = 557.5
# ; (1U): left = 557.5+5 = 562.5. Ends 612.5
# ' (1U): left = 612.5+5 = 617.5. Ends 667.5
# Enter (2.25U=112.5, was 100): left = 667.5+5 = 672.5. Ends 672.5+112.5 = 785.

# ZXCV row
# LShift (2.25U=112.5): left = -25. Ends 87.5.
# Z to / (10*50 + 9*5 = 545): left = 87.5+5 = 92.5. Ends 92.5+545 = 637.5
# RShift (2.75U=137.5, was 137.5): left = 637.5+5 = 642.5. Ends 642.5+137.5 = 780.

# Bottom row (standard 15U width, total key cap width = 15*50 = 750)
# LCtrl (1.25U=62.5): left = -25. Ends 37.5
# LSuper (1.25U=62.5): left = 37.5+5 = 42.5. Ends 105
# LAlt (1.25U=62.5): left = 105+5 = 110. Ends 172.5
# Space (6.25U=312.5): left = 172.5+5 = 177.5. Ends 490
# RAlt (1.25U=62.5): left = 490+5 = 495. Ends 557.5
# RSuper (1.25U=62.5): left = 557.5+5 = 562.5. Ends 625
# Menu (1U=50): left = 625+5 = 630. Ends 680
# RCtrl (1.25U=62.5): left = 680+5 = 685. Ends 747.5.
# This bottom row is the narrowest controlling width: 747.5 - (-25) = 772.5
# Max right coordinate should be 747.5.

# Re-adjusting rightmost keys of other rows to end at 747.5
# F12: left = (F9-F11 block ends 755). F12 left = 755 - 50 = 705. (This is already correct from initial calc)
# Backspace: (Number row ends at 685 before BS). BS left = 685+5 = 690. BS width = 747.5 - 690 = 57.5 (Too small, was 105).
# Let's make Backspace 2U = 100. Num row before BS ends at 685. Backspace left = 685+5=690. Ends 690+100=790.
# This means the main block width is defined by Backspace/Slash row, which is 790.
# Effective width = 790 - (-25) = 815.

# Let's use the original commenter's x values as intended centers, then convert, then fix overlaps.
# This re-evaluation is complex. I will proceed with the initial logic:
# 1. Rename x to left, y to top.
# 2. Convert: new_left = old_x - width/2, new_top = old_y - height/2.
# 3. Manually adjust a few obvious overlaps based on visual reasoning of a TKL.
# The previous detailed re-layout attempt is too complex for one step.
