[[key]]
name = "Esc"
left = 0.0
top = 0.0
width = 50.0
height = 50.0
keycode = "esc"

[[key]]
name = "F1"
left = 80.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f1"

[[key]]
name = "F2"
left = 135.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f2"

[[key]]
name = "F3"
left = 190.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f3"

[[key]]
name = "F4"
left = 245.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f4"

[[key]]
name = "F5"
left = 325.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f5"

[[key]]
name = "F6"
left = 380.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f6"

[[key]]
name = "F7"
left = 435.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f7"

[[key]]
name = "F8"
left = 490.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f8"

[[key]]
name = "F9"
left = 570.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f9"

[[key]]
name = "F10"
left = 625.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f10"

[[key]]
name = "F11"
left = 680.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f11"

[[key]]
name = "F12"
left = 735.0
top = 0.0
width = 50.0
height = 50.0
keycode = "f12"

[[key]]
name = "`"
left = 0.0
top = 55.0
width = 50.0
height = 50.0
keycode = "grave"

[[key]]
name = "1"
left = 55.0
top = 55.0
width = 50.0
height = 50.0
keycode = "1"

[[key]]
name = "2"
left = 110.0
top = 55.0
width = 50.0
height = 50.0
keycode = "2"

[[key]]
name = "3"
left = 165.0
top = 55.0
width = 50.0
height = 50.0
keycode = "3"

[[key]]
name = "4"
left = 220.0
top = 55.0
width = 50.0
height = 50.0
keycode = "4"

[[key]]
name = "5"
left = 275.0
top = 55.0
width = 50.0
height = 50.0
keycode = "5"

[[key]]
name = "6"
left = 330.0
top = 55.0
width = 50.0
height = 50.0
keycode = "6"

[[key]]
name = "7"
left = 385.0
top = 55.0
width = 50.0
height = 50.0
keycode = "7"

[[key]]
name = "8"
left = 440.0
top = 55.0
width = 50.0
height = 50.0
keycode = "8"

[[key]]
name = "9"
left = 495.0
top = 55.0
width = 50.0
height = 50.0
keycode = "9"

[[key]]
name = "0"
left = 550.0
top = 55.0
width = 50.0
height = 50.0
keycode = "0"

[[key]]
name = "-"
left = 605.0
top = 55.0
width = 50.0
height = 50.0
keycode = "minus"

[[key]]
name = "="
left = 660.0
top = 55.0
width = 50.0
height = 50.0
keycode = "equal"

[[key]]
name = "Backspace"
left = 715.0
top = 55.0
width = 100.0
height = 50.0
keycode = "backspace"

[[key]]
name = "Tab"
left = 0.0
top = 110.0
width = 75.0
height = 50.0
keycode = "tab"

[[key]]
name = "Q"
left = 80.0
top = 110.0
width = 50.0
height = 50.0
keycode = "q"

[[key]]
name = "W"
left = 135.0
top = 110.0
width = 50.0
height = 50.0
keycode = "w"

[[key]]
name = "E"
left = 190.0
top = 110.0
width = 50.0
height = 50.0
keycode = "e"

[[key]]
name = "R"
left = 245.0
top = 110.0
width = 50.0
height = 50.0
keycode = "r"

[[key]]
name = "T"
left = 300.0
top = 110.0
width = 50.0
height = 50.0
keycode = "t"

[[key]]
name = "Y"
left = 355.0
top = 110.0
width = 50.0
height = 50.0
keycode = "y"

[[key]]
name = "U"
left = 410.0
top = 110.0
width = 50.0
height = 50.0
keycode = "u"

[[key]]
name = "I"
left = 465.0
top = 110.0
width = 50.0
height = 50.0
keycode = "i"

[[key]]
name = "O"
left = 520.0
top = 110.0
width = 50.0
height = 50.0
keycode = "o"

[[key]]
name = "P"
left = 575.0
top = 110.0
width = 50.0
height = 50.0
keycode = "p"

[[key]]
name = "["
left = 630.0
top = 110.0
width = 50.0
height = 50.0
keycode = "leftbrace"

[[key]]
name = "]"
left = 685.0
top = 110.0
width = 50.0
height = 50.0
keycode = "rightbrace"

[[key]]
name = "\\"
left = 740.0
top = 110.0
width = 75.0
height = 50.0
keycode = "backslash"

[[key]]
name = "Caps Lock"
left = 0.0
top = 165.0
width = 87.5
height = 50.0
keycode = "capslock"

[[key]]
name = "A"
left = 92.5
top = 165.0
width = 50.0
height = 50.0
keycode = "a"

[[key]]
name = "S"
left = 147.5
top = 165.0
width = 50.0
height = 50.0
keycode = "s"

[[key]]
name = "D"
left = 202.5
top = 165.0
width = 50.0
height = 50.0
keycode = "d"

[[key]]
name = "F"
left = 257.5
top = 165.0
width = 50.0
height = 50.0
keycode = "f"

[[key]]
name = "G"
left = 312.5
top = 165.0
width = 50.0
height = 50.0
keycode = "g"

[[key]]
name = "H"
left = 367.5
top = 165.0
width = 50.0
height = 50.0
keycode = "h"

[[key]]
name = "J"
left = 422.5
top = 165.0
width = 50.0
height = 50.0
keycode = "j"

[[key]]
name = "K"
left = 477.5
top = 165.0
width = 50.0
height = 50.0
keycode = "k"

[[key]]
name = "L"
left = 532.5
top = 165.0
width = 50.0
height = 50.0
keycode = "l"

[[key]]
name = ";"
left = 587.5
top = 165.0
width = 50.0
height = 50.0
keycode = "semicolon"

[[key]]
name = "'"
left = 642.5
top = 165.0
width = 50.0
height = 50.0
keycode = "apostrophe"

[[key]]
name = "Enter"
left = 697.5
top = 165.0
width = 117.5
height = 50.0
keycode = "enter"

[[key]]
name = "Shift"
left = 0.0
top = 220.0
width = 112.5
height = 50.0
keycode = "leftshift"

[[key]]
name = "Z"
left = 117.5
top = 220.0
width = 50.0
height = 50.0
keycode = "z"

[[key]]
name = "X"
left = 172.5
top = 220.0
width = 50.0
height = 50.0
keycode = "x"

[[key]]
name = "C"
left = 227.5
top = 220.0
width = 50.0
height = 50.0
keycode = "c"

[[key]]
name = "V"
left = 282.5
top = 220.0
width = 50.0
height = 50.0
keycode = "v"

[[key]]
name = "B"
left = 337.5
top = 220.0
width = 50.0
height = 50.0
keycode = "b"

[[key]]
name = "N"
left = 392.5
top = 220.0
width = 50.0
height = 50.0
keycode = "n"

[[key]]
name = "M"
left = 447.5
top = 220.0
width = 50.0
height = 50.0
keycode = "m"

[[key]]
name = ","
left = 502.5
top = 220.0
width = 50.0
height = 50.0
keycode = "comma"

[[key]]
name = "."
left = 557.5
top = 220.0
width = 50.0
height = 50.0
keycode = "dot"

[[key]]
name = "/"
left = 612.5
top = 220.0
width = 50.0
height = 50.0
keycode = "slash"

[[key]]
name = "Shift"
left = 667.5
top = 220.0
width = 147.5
height = 50.0
keycode = "rightshift"

[[key]]
name = "Ctrl"
left = 0.0
top = 275.0
width = 62.5
height = 50.0
keycode = "leftctrl"

[[key]]
name = "Super"
left = 67.5
top = 275.0
width = 62.5
height = 50.0
keycode = "leftmeta"

[[key]]
name = "Alt"
left = 135.0
top = 275.0
width = 62.5
height = 50.0
keycode = "leftalt"

[[key]]
name = "Space"
left = 202.5
top = 275.0
width = 312.5
height = 50.0
keycode = "space"

[[key]]
name = "Alt"
left = 520.0
top = 275.0
width = 62.5
height = 50.0
keycode = "rightalt"

[[key]]
name = "Super"
left = 587.5
top = 275.0
width = 62.5
height = 50.0
keycode = "rightmeta"

[[key]]
name = "Menu"
left = 655.0
top = 275.0
width = 62.5
height = 50.0
keycode = "menu"

[[key]]
name = "Ctrl"
left = 722.5
top = 275.0
width = 92.5
height = 50.0
keycode = "rightctrl"

[[key]]
name = "PrtSc"
left = 845.0
top = 0.0
width = 50.0
height = 50.0
keycode = "printscreen"

[[key]]
name = "ScrLk"
left = 900.0
top = 0.0
width = 50.0
height = 50.0
keycode = "scrolllock"

[[key]]
name = "Pause"
left = 955.0
top = 0.0
width = 50.0
height = 50.0
keycode = "pause"

[[key]]
name = "Ins"
left = 845.0
top = 55.0
width = 50.0
height = 50.0
keycode = "insert"

[[key]]
name = "Home"
left = 900.0
top = 55.0
width = 50.0
height = 50.0
keycode = "home"

[[key]]
name = "PgUp"
left = 955.0
top = 55.0
width = 50.0
height = 50.0
keycode = "pageup"

[[key]]
name = "Del"
left = 845.0
top = 110.0
width = 50.0
height = 50.0
keycode = "delete"

[[key]]
name = "End"
left = 900.0
top = 110.0
width = 50.0
height = 50.0
keycode = "end"

[[key]]
name = "PgDn"
left = 955.0
top = 110.0
width = 50.0
height = 50.0
keycode = "pagedown"

[[key]]
name = "Up"
left = 900.0
top = 220.0
width = 50.0
height = 50.0
keycode = "up"

[[key]]
name = "Left"
left = 845.0
top = 275.0
width = 50.0
height = 50.0
keycode = "left"

[[key]]
name = "Down"
left = 900.0
top = 275.0
width = 50.0
height = 50.0
keycode = "down"

[[key]]
name = "Right"
left = 955.0
top = 275.0
width = 50.0
height = 50.0
keycode = "right"
